const mongoose = require("mongoose");

const settingsSchema = new mongoose.Schema({
  admin: {
    type: mongoose.Types.ObjectId,
    ref: "User",
    required: true,
  },
  managers: [
    {
      type: mongoose.Types.ObjectId,
      ref: "Trainer",
    },
  ],
  adminsAllowedPaths: {
    type: [String],
    default: ["*"],
  },
  managersAllowedPaths: {
    type: [String],
    // TODO: add method checks - see below
    // default: [
    //   {method:"get", path: "/clients"},
    // ],
    default: [
      "/clients",
      "/clients/:id",
      "/clients/:id/username",
      "/clients/:id/email",
      "/clients/:id/password",
      "/clients/:id/image",
      "/clients/:id/name",
      "/clients/:id/phone",
      "/clients/:id/target",
      "/clients/:id/food-regime",
      "/clients/:id/notes",
      "/clients/:id/status",
      "/clients/:id/cards",
      "/clients/:id/cards/:id",
      "/clients/:id/cards/:id/type",
      "/clients/:id/cards/:id/start",
      "/clients/:id/cards/:id/end",
      "/clients/:id/cards/:id/trainings-left",
      "/clients/:id/cards/:id/trainer",
      "/clients/:id/cards/:id/notes",
      "/clients/:id/cards/:id/paid",
      "/clients/:id/cards/:id/status",
      "/clients/:id/cards/:id/trainings",
      "/clients/:id/cards/:id/trainings/:id",
      "/clients/:id/measurements",
      "/clients/:id/measurements/:id",
      "/clients/:id/measurements/:id/notes",
      "/trainers",
      "/trainers/:id",
      "/trainers/:id/username",
      "/trainers/:id/email",
      "/trainers/:id/password",
      "/trainers/:id/image",
      "/trainers/:id/name",
      "/trainers/:id/phone",
      "/trainers/:id/target",
      "/trainers/:id/food-regime",
      "/trainers/:id/notes",
      "/trainers/:id/status",
      "/measures",
    ],
  },
  trainersAllowedPaths: {
    type: [String],
    default: [
      "/clients",
      "/clients/:id",
      "/clients/:id/username",
      "/clients/:id/email",
      "/clients/:id/password",
      "/clients/:id/image",
      "/clients/:id/name",
      "/clients/:id/phone",
      "/clients/:id/target",
      "/clients/:id/food-regime",
      "/clients/:id/notes",
      "/clients/:id/status",
      "/clients/:id/cards",
      "/clients/:id/cards/:id",
      "/clients/:id/cards/:id/type",
      "/clients/:id/cards/:id/start",
      "/clients/:id/cards/:id/end",
      "/clients/:id/cards/:id/trainings-left",
      "/clients/:id/cards/:id/trainer",
      "/clients/:id/cards/:id/notes",
      "/clients/:id/cards/:id/paid",
      "/clients/:id/cards/:id/status",
      "/clients/:id/cards/:id/trainings",
      "/clients/:id/cards/:id/trainings/:id",
      "/clients/:id/measurements",
      "/clients/:id/measurements/:id",
      "/clients/:id/measurements/:id/notes",
    ],
  },
  clientsAllowedPaths: {
    type: [String],
    default: [
      "/clients",
      "/clients/:id",
      "/clients/:id/username",
      "/clients/:id/email",
      "/clients/:id/password",
      "/clients/:id/image",
      "/clients/:id/name",
      "/clients/:id/phone",
      "/clients/:id/target",
      "/clients/:id/food-regime",
      "/clients/:id/notes",
      "/clients/:id/status",
      "/clients/:id/cards",
      "/clients/:id/cards/:id",
      "/clients/:id/cards/:id/type",
      "/clients/:id/cards/:id/start",
      "/clients/:id/cards/:id/end",
      "/clients/:id/cards/:id/trainings-left",
      "/clients/:id/cards/:id/trainer",
      "/clients/:id/cards/:id/notes",
      "/clients/:id/cards/:id/paid",
      "/clients/:id/cards/:id/status",
      "/clients/:id/cards/:id/trainings",
      "/clients/:id/cards/:id/trainings/:id",
      "/clients/:id/measurements",
      "/clients/:id/measurements/:id",
      "/clients/:id/measurements/:id/notes",
    ],
  },
  guestsAllowedPaths: {
    type: [String],
    default: ["/auth", "/auth/login"],
  },
  passwordsMinLength: {
    type: Number,
    min: 4,
    max: 20,
    default: 6,
  },
  passwordsMaxLength: {
    type: Number,
    min: 4,
    max: 20,
    default: 10,
  },
});

const Settings = mongoose.model("Settings", settingsSchema);

module.exports = Settings;
